// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import {themes as prismThemes} from 'prism-react-renderer';
import * as path from "node:path";
import sidebars from './sidebars.js';
import sidebarsV6 from './sidebars-v6.js';
import sidebarsDeveloperV6 from './sidebars-developer-v6.js';

function normalizeDirName(dirName) {
    return String(dirName).replace(/\\/g, '/').replace(/^\/+|\/+$/g, '');
}

function buildHiddenAutogeneratedIndexMap(items) {
    /** @type {Map<string, string>} */
    const hidden = new Map();

    function visit(sidebarItems) {
        for (const sidebarItem of sidebarItems) {
            if (typeof sidebarItem === 'string' || !sidebarItem || sidebarItem.type !== 'category') {
                continue;
            }

            const linkId = sidebarItem.link?.type === 'doc' ? sidebarItem.link.id : undefined;
            const nestedItems = Array.isArray(sidebarItem.items) ? sidebarItem.items : [];

            if (linkId) {
                for (const nestedItem of nestedItems) {
                    if (nestedItem?.type !== 'autogenerated' || !nestedItem.dirName) {
                        continue;
                    }
                    const dirName = normalizeDirName(nestedItem.dirName);
                    const expectedIndexId = `${dirName}/index`;
                    if (linkId === expectedIndexId) {
                        hidden.set(dirName, expectedIndexId);
                    }
                }
            }

            visit(nestedItems);
        }
    }

    visit(items);
    return hidden;
}

const v6HiddenAutogeneratedIndexByDir = buildHiddenAutogeneratedIndexMap(sidebarsV6.docSidebarV6);
const docsHiddenAutogeneratedIndexByDir = buildHiddenAutogeneratedIndexMap(sidebars.docSidebar);
const developerV6HiddenAutogeneratedIndexByDir = buildHiddenAutogeneratedIndexMap(
    sidebarsDeveloperV6.developerSidebarV6,
);

function createSidebarItemsGenerator(hiddenAutogeneratedIndexByDir) {
    return async ({defaultSidebarItemsGenerator, ...args}) => {
        const items = await defaultSidebarItemsGenerator(args);
        const dirName =
            args.item?.type === 'autogenerated' && args.item?.dirName
                ? normalizeDirName(args.item.dirName)
                : undefined;
        const hiddenIndexId = dirName
            ? hiddenAutogeneratedIndexByDir.get(dirName)
            : undefined;
        if (hiddenIndexId) {
            return items.filter(
                (item) => !(item.type === 'doc' && item.id === hiddenIndexId),
            );
        }
        return items;
    };
}

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/types').Config} */
const config = {
    title: 'J2Commerce Documentation',
    tagline: 'The best up-to-date documentation for J2Commerce',
    favicon: 'img/shortcut.webp',

    // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
    future: {
        v4: true, // Improve compatibility with the upcoming Docusaurus v4
    },

    markdown: {
        mermaid: true,
    },
    themes: ['@docusaurus/theme-mermaid'],
    clientModules: [
        path.resolve(__dirname, './src/theme/ZoomMermaid.js'),
    ],

    // Set the production url of your site here
    url: 'https://docs.j2commerce.com',
    // Set the /<baseUrl>/ pathname under which your site is served
    // For GitHub pages deployment, it is often '/<projectName>/'
    baseUrl: '/',

    // GitHub pages deployment config.
    // If you aren't using GitHub pages, you don't need these.
    organizationName: 'j2commerce', // Usually your GitHub org/user name.
    projectName: 'documentation', // Usually your repo name.

    onBrokenLinks: 'ignore',
    onBrokenMarkdownLinks: 'warn',

    // Even if you don't use internationalization, you can use this field to set
    // useful metadata like html lang. For example, if your site is Chinese, you
    // may want to replace "en" with "zh-Hans".
    i18n: {
        defaultLocale: 'en',
        locales: ['en'],
    },

    presets: [
        [
            'classic',
            /** @type {import('@docusaurus/preset-classic').Options} */
            ({
                docs: {
                    id: 'docs', // omitted => default instance
                    path: 'docs',
                    routeBasePath: '/',
                    sidebarPath: './sidebars.js',
                    sidebarItemsGenerator: createSidebarItemsGenerator(docsHiddenAutogeneratedIndexByDir),
                    // Please change this to your repo.
                    // Remove this to remove the "edit this page" links.
                    // editUrl: 'https://github.com/j2commerce/documentation/tree/main/',
                },
                blog: false, // Disable blog
                pages: false, // Disable pages
                theme: {
                    customCss: './src/css/custom.css',
                },
            }),
        ],
    ],

    plugins: [
        [
            '@docusaurus/plugin-content-docs',
            {
                id: 'docs-v6', // Unique ID
                path: 'docs-v6', // Source directory for v6 docs
                routeBasePath: 'v6', // URL base path for v6
                sidebarPath: './sidebars-v6.js',
                sidebarItemsGenerator: createSidebarItemsGenerator(v6HiddenAutogeneratedIndexByDir),
            },
        ],
        [
            '@docusaurus/plugin-content-docs',
            {
                id: 'developer-v6', // Unique ID
                path: 'developer-v6', // Source directory for developer docs
                routeBasePath: 'developer', // URL base path: /developer/
                sidebarPath: './sidebars-developer-v6.js',
                sidebarItemsGenerator: createSidebarItemsGenerator(
                    developerV6HiddenAutogeneratedIndexByDir,
                ),
            },
        ],
        [
            'docusaurus-plugin-mcp-server',
            {
                server: {
                    name: 'my-docs',
                    version: '1.0.0',
                },
                // minContentLength: 200, // Skip very short pages
                // excludeRoutes: [
                //   '/404*',
                //   '/search*',
                //   '*/tags/*', // Exclude tag pages
                //   '*/tags', // Exclude tag index pages
                // ],
                indexers: false, // Disable FlexSearch indexer to prevent out of memory errors
            },
        ],
    ],

    themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
        ({
            // Replace with your project's social card
            image: 'img/j2commerce-social-card.jpg',
            navbar: {
                title: 'J2Commerce',
                logo: {
                    alt: 'J2Commerce Logo',
                    src: 'img/shortcut.webp',
                },
                items: [
                    {
                        type: 'docSidebar',
                        docsPluginId: 'docs',
                        sidebarId: 'docSidebar',
                        position: 'left',
                        label: 'Documentation v4',
                        // algolia: {
                        //     indexName: 'j2c_docs',
                        // },
                    },
                    {
                      type: 'docSidebar',
                      docsPluginId: 'docs-v6',
                      sidebarId: 'docSidebarV6',
                      position: 'left',
                      label: 'Documentation v6',
                      // algolia: {
                      //      indexName: 'j2c_docs_v6',
                      // },
                    },
                    // {
                    //   type: 'docSidebar',
                    //   docsPluginId: 'developer-v6',
                    //   sidebarId: 'developerSidebarV6',
                    //   position: 'left',
                    //   label: 'Developer v6',
                    //   algolia: {
                    //        indexName: 'j2c_developer_v6',
                    //    },
                    // },
                ],
            },
            algolia: {
                appId: 'WDTT4PYPY5',
                apiKey: '19df50541882d5ffa3380ff7eb7227b7',
                contextualSearch: false,
                // Runtime index switching is handled in src/theme/SearchBar/index.js.
                indexName: 'j2c_docs',
            },
            footer: {
                style: 'dark',
                copyright: `Copyright © ${new Date().getFullYear()} J2Commerce, LLC. Built with Docusaurus.`,
            },
            prism: {
                theme: prismThemes.github,
                darkTheme: prismThemes.dracula,
            },
        }),
};

export default config;
