// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docSidebarV6: [
        'README',
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
                slug: '/getting-started',
            },
            items: [
                'getting-started/introduction',
                'getting-started/technical-requirements',
                'getting-started/installation',
                'getting-started/getting-started-guide',
                'getting-started/dashboard',
                'getting-started/onboarding',
                'getting-started/store-setup',
                'getting-started/product-category-wizard',
                'getting-started/content-plugin-settings',
            ],
        },
        {
            type: 'category',
            label: 'Catalog',
            link: {
                type: 'generated-index',
                slug: '/catalog',
            },
            items: [
                {
                    type: 'category',
                    label: 'Product Types',
                    link: {
                        type: 'generated-index',
                        slug: '/catalog/product-types',
                    },
                    items: [
                        'catalog/product-types/simple_product',
                        'catalog/product-types/downloadable_product',
                        'catalog/product-types/configurable_product',
                        'catalog/product-types/variable_product',
                        'catalog/product-types/app_flexivariable',
                        'catalog/product-types/app_bundleproduct',
                        'catalog/product-types/subscriptionproduct',
                        'catalog/product-types/app_boxbuilderproduct',
                    ],
                },
                'catalog/content-j2commerce',
                'catalog/creating-options',
                'catalog/creating-filters',
            ],
        },
        {
            type: 'category',
            label: 'Sales',
            link: {
                type: 'doc',
                id: 'sales/index',
            },
            items: [
                'sales/orders',
                'sales/customers',
                'sales/coupons',
            ],
        },
        {
            type: 'category',
            label: 'Localisation',
            link: {
                type: 'doc',
                id: 'localization/index',
            },
            items: [
                'localization/countries',
                'localization/zones',
                'localization/geozones',
                'localization/currencies',
                'localization/tax-rates',
                'localization/tax-profiles',
                'localization/lengths',
                'localization/weights',

            ],
        },
        {
            type: 'category',
            label: 'Taxation',
            link: {
                type: 'doc',
                id: 'taxation/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'taxation',
                },
            ],
        },
        {
            type: 'category',
            label: 'Design',
            link: {
                type: 'generated-index',
                slug: '/design',
            },
            items: [
                {
                    type: 'category',
                    label: 'Layout Overrides',
                    link: {
                        type: 'generated-index',
                        slug: '/design/layout-overrides',
                    },
                    items: [
                        'design/layout-overrides/app-overrides',
                        'design/layout-overrides/shipping-payment-overrides',
                    ],
                },
                'design/template-overrides',
                'design/email-templates',
                'design/invoice-templates',
                'design/creating-tags',
            ],
        },
        {
            type: 'category',
            label: 'Setup',
            link: {
                type: 'generated-index',
                slug: '/setup',
            },
            items: [
                {
                    type: 'category',
                    label: 'Configuration',
                    link: {
                        type: 'generated-index',
                        slug: '/setup/configuration',
                    },
                    items: [
                        'setup/configuration/cron-tasks',
                    ],
                },
                'setup/custom-fields',
                'setup/order-statuses',
            ],
        },
        {
            type: 'category',
            label: 'Apps and Extensions',
            link: {
                type: 'doc',
                id: 'apps-and-extensions/index',
            },
            items: [
                {
                    type: 'category',
                    label: 'Apps',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/apps',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/apps',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Modules',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/modules',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/modules',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Plugins',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/plugins',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/plugins',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Payment Methods',
            link: {
                type: 'generated-index',
                slug: '/payment-methods', // Custom slug removes /category prefix
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'payment-methods',
                },
            ],
        },
        {
            type: 'category',
            label: 'Shipping Methods',
            link: {
                type: 'generated-index',
                slug: '/shipping-methods',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'shipping-methods',
                },
            ],
        },
        {
            type: 'category',
            label: 'Reports',
            link: {
                type: 'doc',
                id: 'reports/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'reports',
                },
            ],
        },
        {
            type: 'category',
            label: 'J2Commerce Chat',
            link: {
                type: 'generated-index',
                slug: '/j2commerce-chat',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'j2commerce-chat',
                },
            ],
        },
        'plg_system_j2commercemcp',
        'rest-api',
    ],
};

export default sidebars;
