// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docSidebarV6: [
        'README',
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
                slug: '/getting-started',
            },
            items: [
                'getting-started/introduction',
                'getting-started/technical-requirements',
                'getting-started/installation',
                'getting-started/getting-started-guide',
                'getting-started/dashboard',
                'getting-started/onboarding',
                'getting-started/store-setup',
                'getting-started/product-category-wizard',
                'getting-started/content-plugin-settings',
            ],
        },
        {
            type: 'category',
            label: 'Migration Tools',
            link: {
                type: 'generated-index',
                slug: '/migration-tools',
            },
            items: [
                'migration-tools/com_j2commercemigrator',
                'migration-tools/plg_j2commercemigrator_j2commerce4',
                'migration-tools/virtuemart3',
                'migration-tools/woocommerce',
            ],
        },
        {
            type: 'category',
            label: 'Catalog',
            link: {
                type: 'generated-index',
                slug: '/catalog',
            },
            items: [
                {
                    type: 'category',
                    label: 'Product Types',
                    link: {
                        type: 'generated-index',
                        slug: '/catalog/product-types',
                    },
                    items: [
                        'catalog/product-types/simple_product',
                        'catalog/product-types/downloadable_product',
                        'catalog/product-types/configurable_product',
                        'catalog/product-types/variable_product',
                        'catalog/product-types/app_flexivariable',
                        'catalog/product-types/app_bundleproduct',
                        'catalog/product-types/subscriptionproduct',
                        'catalog/product-types/app_boxbuilderproduct',
                    ],
                },
                'catalog/managing-products',
                'catalog/content-j2commerce',
                'catalog/inventory',
                'catalog/advanced-pricing',
                'catalog/creating-options',
                {
                    type: 'category',
                    label: 'Vendors',
                    link: {
                        type: 'doc',
                        id: 'catalog/vendors/index',
                    },
                    items: [],
                },
                {
                    type: 'category',
                    label: 'Manufacturers',
                    link: {
                        type: 'doc',
                        id: 'catalog/manufacturers/index',
                    },
                    items: [],
                },
                'catalog/creating-filters',
            ],
        },
        {
            type: 'category',
            label: 'Sales',
            link: {
                type: 'doc',
                id: 'sales/index',
            },
            items: [
                'sales/orders',
                'sales/customers',
                'sales/coupons',
                'sales/vouchers',
            ],
        },
        {
            type: 'category',
            label: 'Localisation',
            link: {
                type: 'doc',
                id: 'localization/index',
            },
            items: [
                'localization/countries',
                'localization/zones',
                'localization/geozones',
                'localization/currencies',
                'localization/tax-rates',
                'localization/tax-profiles',
                'localization/lengths',
                'localization/weights',
            ],
        },
        {
            type: 'category',
            label: 'Taxation',
            link: {
                type: 'doc',
                id: 'taxation/index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'taxation',
                },
            ],
        },
        {
            type: 'category',
            label: 'Design',
            link: {
                type: 'doc',
                id: 'design/index',
            },
            items: [
                {
                    type: 'category',
                    label: 'Layouts',
                    link: {
                        type: 'doc',
                        id: 'design/layouts/index',
                    },
                    items: [
                        'design/layouts/bootstrap5-layouts',
                        'design/layouts/uikit-layouts',
                    ],
                },
                {
                    type: 'category',
                    label: 'Layout Overrides',
                    link: {
                        type: 'generated-index',
                        slug: '/design/layout-overrides',
                    },
                    items: [
                        'design/layout-overrides/app-overrides',
                        'design/layout-overrides/shipping-payment-overrides',
                    ],
                },
                'design/template-overrides',
                'design/email-templates',
                'design/invoice-templates',
                'design/creating-tags',
            ],
        },
        {
            type: 'category',
            label: 'Setup',
            link: {
                type: 'generated-index',
                slug: '/setup',
            },
            items: [
                {
                    type: 'category',
                    label: 'Configuration',
                    link: {
                        type: 'generated-index',
                        slug: '/setup/configuration',
                    },
                    items: [
                        'setup/configuration/cron-tasks',
                    ],
                },
                'setup/custom-fields',
                'setup/uikit3-custom-fields',
                'setup/order-statuses',
                'setup/shipping-troubleshooter',
                'setup/queue-hub',
            ],
        },
        {
            type: 'category',
            label: 'Apps and Extensions',
            link: {
                type: 'doc',
                id: 'apps-and-extensions/index',
            },
            items: [
                {
                    type: 'category',
                    label: 'Apps',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/apps',
                    },
                    items: [
                        // Add to User Group
                        'apps-and-extensions/apps/usergroup',
                        // Additional Fees
                        'apps-and-extensions/apps/additional_fee',
                        // Additional Terms
                        'apps-and-extensions/apps/additionalterms',
                        // Address Autocomplete
                        'apps-and-extensions/apps/app-addressautocomplete',
                        // Already Purchased Badge
                        'apps-and-extensions/apps/app_alreadypurchased',
                        // Advanced Cart Drawer
                        'apps-and-extensions/apps/advancedcart',
                        // Advanced Tax Rates (there is a duplicate)
                        'apps-and-extensions/apps/taxrate',
                        // Akeeba Release System Download ID (there is a duplicate)
                        'apps-and-extensions/apps/app-arsdlid',
                        // Ask Question / Quote
                        'apps-and-extensions/apps/app-productquote',
                        // Algolia Search Integration
                        'apps-and-extensions/apps/algolia',
                        // Auto-Coupon Pop Up
                        'apps-and-extensions/apps/auto-coupon',
                        // Availability Notification
                        'apps-and-extensions/apps/outofstockemail',
                        // Avalara AvaTax
                        'apps-and-extensions/apps/avalaratax',
                        // BaseLinker Integration
                        'apps-and-extensions/apps/app-baselinker',
                        // Bulk Discounts
                        'apps-and-extensions/apps/app-bulkdiscount',
                        // Calculator - Sort by Price
                        'apps-and-extensions/apps/app_calculatorsortbyprice',
                        // Change Password
                        'apps-and-extensions/apps/app_changepasswords',
                        // Clover POS Integration
                        'apps-and-extensions/apps/app_cloverpos',
                        // Conditional Payment Methods
                        'apps-and-extensions/apps/app_conditionalpayment',
                        // Content Fields
                        'apps-and-extensions/apps/contentfields',
                        // Currency Exchange Rates Updater
                        'apps-and-extensions/apps/app_currencyupdater',
                        // Custom Accordions
                        'apps-and-extensions/apps/custom-accordions',
                        // Custom Tabs
                        'apps-and-extensions/apps/custom-tabs',
                        // Customers Also Bought
                        'apps-and-extensions/apps/app_customerbought',
                        // Data Validation
                        'apps-and-extensions/apps/app-validationrules',
                        // DigiFactu — VERI*FACTU E-Invoicing
                        'apps-and-extensions/apps/digifactu',
                        // Donation
                        'apps-and-extensions/apps/app-donation',
                        // Dropbox
                        'apps-and-extensions/apps/app_dropbox',
                        // Easy Links
                        'apps-and-extensions/apps/app_easylinks',
                        // Easy Reorder
                        'apps-and-extensions/apps/app_reorder',
                        // Email Cart
                        'apps-and-extensions/apps/app-emailbasket',
                        // EU Order Withdrawal Compliance
                        'apps-and-extensions/apps/orderwithdrawal',
                        // EU VAT Rules
                        'apps-and-extensions/apps/euvat',
                        // ExpertVoice Recommendations
                        'apps-and-extensions/apps/app-expertvoice',
                        // Meta Pixel / Facebook Conversion
                        'apps-and-extensions/apps/app_facebookconversion',
                        // Findbar
                        'apps-and-extensions/apps/app_findbar',
                        // GDPR Compliance
                        'apps-and-extensions/apps/app-gdpr',
                        // Gift Wrapping
                        'apps-and-extensions/apps/app-giftwrapping',
                        // Google Merchant Feed
                        'apps-and-extensions/apps/app_googlemerchantfeed',
                        // Google Tag Manager
                        'apps-and-extensions/apps/ecommercegoogletagmanager',
                        // Heureka Product Feed
                        'apps-and-extensions/apps/app_heurekaproductfeed',
                        // Inventory Email Notifications
                        'apps-and-extensions/apps/stocknotification',
                        // Klaviyo Integration
                        'apps-and-extensions/apps/klaviyo',
                        // Markdown for AI Agents
                        'apps-and-extensions/apps/app_markdown',
                        // Minimum Order Restriction
                        'apps-and-extensions/apps/minimumorder',
                        // Modal Bouncer
                        'apps-and-extensions/apps/app_modalbouncer',
                        // Omnisend Integration
                        'apps-and-extensions/apps/app_omnisend',
                        // Opening Hours
                        'apps-and-extensions/apps/openinghours',
                        // Order Files
                        'apps-and-extensions/apps/orderfiles',
                        // Partial Payment
                        'apps-and-extensions/apps/partialpayment',
                        // Pay Later / Pay Against Invoice
                        'apps-and-extensions/apps/app-profileorder',
                        // Payment Method Discount
                        'apps-and-extensions/apps/paymentdiscount',
                        // Payment Method Restrictions
                        'apps-and-extensions/apps/app-restrictpayment',
                        // PDF Invoices
                        'apps-and-extensions/apps/pdfinvoices',
                        // Points and Rewards
                        'apps-and-extensions/apps/points-rewards',
                        // Price Texts
                        'apps-and-extensions/apps/pricetexts',
                        // Printify Print-on-Demand
                        'apps-and-extensions/apps/app_printify',
                        // PrintNode for J2Commerce
                        'apps-and-extensions/apps/printnode',
                        // Product Compare
                        'apps-and-extensions/apps/productcompare',
                        // Product Navbar
                        'apps-and-extensions/apps/app_productnavbar',
                        // Product Reviews
                        'apps-and-extensions/apps/app-reviews',
                        // Product Shipping Restrictions
                        'apps-and-extensions/apps/app-restrictbyshipping',
                        // Quantity Discounts
                        'apps-and-extensions/apps/qtydiscount',
                        // Quantity Dropdown
                        'apps-and-extensions/apps/quantityprice',
                        // Related Category Products
                        'apps-and-extensions/apps/relatedcategoryproducts',
                        // ShipStation Integration
                        'apps-and-extensions/apps/shipstation',
                        // Simple CSV Import
                        'apps-and-extensions/apps/simple-csv-import',
                        // Social Media Sharing
                        'apps-and-extensions/apps/app-socialmedia',
                        // Square Integration (there is a duplicate)
                        'apps-and-extensions/apps/square-integration',
                        // Storepoint Store Locator
                        'apps-and-extensions/apps/storepoint',
                        // Subscription - Exclude Renewal Inventory
                        'apps-and-extensions/apps/subscriptionexcluderenewalinventory',
                        // Subscription Extra Fields
                        'apps-and-extensions/apps/subscriptionextrafields',
                        // Subscription Multiple Quantity
                        'apps-and-extensions/apps/subscriptionmultiplequantity',
                        // Tax Manager
                        'apps-and-extensions/apps/app_taxmanager',
                        // TrackingMore Integration
                        'apps-and-extensions/apps/app_trackingmore',
                        // Twilio SMS Notifications
                        'apps-and-extensions/apps/twilio',
                        // User Group Tax Exemptions
                        'apps-and-extensions/apps/app-usertaxexemptions',
                        // Veeqo
                        'apps-and-extensions/apps/app_veeqo',
                        // Vendor Management
                        'apps-and-extensions/apps/app_vendormanagement',
                        // Video Display
                        'apps-and-extensions/apps/app_videodisplay',
                        // Wishlist
                        'apps-and-extensions/apps/app-wishlist',
                    ],
                },
                {
                    type: 'category',
                    label: 'Modules',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/modules',
                    },
                    items: [
                        // Algolia Search Module
                        'apps-and-extensions/modules/mod_j2commerce_algoliasearch',
                        // Categories Module
                        'apps-and-extensions/modules/mod_j2commerce_categories',
                        // Currencies
                        'apps-and-extensions/modules/mod_j2commerce_currency',
                        // Products Module
                        'apps-and-extensions/modules/mod_j2commerce_products',
                        // Wishlist Module
                        'apps-and-extensions/modules/mod_j2commerce_wishlist',
                    ],
                },
                {
                    type: 'category',
                    label: 'Plugins',
                    link: {
                        type: 'generated-index',
                        slug: '/apps-and-extensions/plugins',
                    },
                    items: [
                        // Action Log Plugin
                        'apps-and-extensions/plugins/plg_actionlog_j2commerce',
                        // J2Commerce CLI
                        'apps-and-extensions/plugins/plg_console_j2commerce',
                        // J2Commerce MCP Server
                        'apps-and-extensions/plugins/plg_system_j2commercemcp',
                        // J2Commerce Migration Tool
                        'apps-and-extensions/plugins/plg_system_j2commerce_migration_tool',
                        // OSMap - J2Commerce
                        'apps-and-extensions/plugins/osmap-j2commerce',
                        // Sample Data Plugin
                        'apps-and-extensions/plugins/plg_sampledata_j2commerce',
                        // Schema.org - Ecommerce
                        'apps-and-extensions/plugins/plg_schemaorg_ecommerce',
                        // Scheduled Tasks
                        'apps-and-extensions/plugins/plg_task_j2commerce',
                        // Smart Search Plugin for J2Commerce
                        'apps-and-extensions/plugins/plg_finder_j2commerce',
                        // Web Services - J2Commerce
                        'apps-and-extensions/plugins/plg_webservices_j2commerce',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Payment Methods',
            link: {
                type: 'generated-index',
                slug: '/payment-methods', // Custom slug removes /category prefix
            },
            items: [
                // 2Checkout (Verifone) — Legacy Redirect Gateway
                'payment-methods/2checkout',
                // Adyen Payment
                'payment-methods/payment_adyen',
                // Affirm
                'payment-methods/payment_affirm',
                // Alipay Payment
                'payment-methods/alipay',
                // Amazon Pay
                'payment-methods/payment_amazonpay',
                // Authorize.Net Payment Plugin
                'payment-methods/authorize-net',
                // Bank Transfer Payment
                'payment-methods/payment_banktransfer',
                // Barclaycard ePDQ Payment
                'payment-methods/payment_barclays',
                // Braintree Payment
                'payment-methods/braintree',
                //'payment-methods/payment_braintree',
                // CardSave / Worldpay Legacy Gateway
                //'payment-methods/cardsave',
                // Cardsave Payment
                'payment-methods/payment_cardsave',
                // Cash on Delivery Payment
                'payment-methods/payment_cash',
                // CCAvenue Payment
                'payment-methods/payment_ccavenue',
                // CECA Payment (Cecabank TPV)
                'payment-methods/payment_ceca',
                // Checkout Finland (Paytrail)
                'payment-methods/checkoutfi',
                // Clover Payment
                'payment-methods/payment_clover',
                // Coinbase Commerce
                'payment-methods/coinbase',
                // Conekta Payment
                'payment-methods/conekta',
                // Credova Financing
                'payment-methods/payment_credova',
                // Culqi Payment Gateway
                'payment-methods/culqi',
                // Dib Easy
                'payment-methods/payment_dibseasy',
                // Dojo Payment
                'payment-methods/payment-dojo',
                // Elavon Converge Payment
                'payment-methods/elavon',
                // Elavon Payment Gateway
                //'payment-methods/payment_elavon',
                // ePDQ / Worldline Hosted Payment Page
                'payment-methods/epdq',
                // eWAY Rapid Payment
                'payment-methods/ewayrapid',
                // Finix Payment
                'payment-methods/payment_finix',
                // Fiserv Commerce Hub Payment
                'payment-methods/payment_fiserv',
                // First Data (Global Gateway e4 / IPG Connect)
                'payment-methods/firstdata',
                // Flo2Cash Web2Pay
                'payment-methods/flo2cash',
                // GestPay / Axerve (Banca Sella) Payment
                'payment-methods/gestpay',
                // Global Payments
                'payment-methods/payment_globalpayments',
                // Icepay
                'payment-methods/icepay',
                // Klarna Payment
                'payment-methods/payment_klarna',
                // Klarna Invoice (Pay Later)
                'payment-methods/payment_klarnainvoice',
                // Kustom Payment
                'payment-methods/payment_kustom',
                // Lemon Squeezy Payment
                'payment-methods/payment_lemonsqueezy',
                // Mercury ACH Bank Payment
                'payment-methods/payment_mercury',
                // Mollie Payments
                'payment-methods/payment_mollie',
                // Moneris Checkout
                'payment-methods/moneris',
                // Money Order / Check Payment
                'payment-methods/payment_moneyorder',
                // Moyasar Payment
                'payment-methods/payment_moyasar',
                // MultiSafepay
                'payment-methods/multisafepay',
                // NMI Payment
                'payment-methods/payment_nmi',
                // Nochex
                'payment-methods/payment_nochex',
                // Opayo (Sage Pay) Card Payments
                'payment-methods/payment_opayo',
                // Paybox
                'payment-methods/payment_paybox',
                // Paygate
                'payment-methods/payment_paygate',
                // Paynl
                'payment-methods/payment_paynl',
                // Paddle Payment Plugin
                'payment-methods/payment_paddle',
                // Payeezy
                'payment-methods/payeezy',
                // Payfast Payment
                'payment-methods/payment_payfast',
                // PayMate
                'payment-methods/paymate',
                // PAYONE Commerce Platform Payment
                'payment-methods/payment_payone',
                // PayPal Payment
                'payment-methods/payment_paypal',
                // PayPal Complete
                'payment-methods/payment_paypalcomplete',
                // Paysafe Payment
                'payment-methods/payment_paysafe',
                // PayTabs Payment
                'payment-methods/payment_paytabs',
                // PayTrace
                'payment-methods/payment_paytrace',
                // PublicSquare Payment
                'payment-methods/payment_publicsquare',
                // Purchase Order Payment
                'payment-methods/payment_purchaseorder',
                // QuickBooks Payments
                'payment-methods/payment_quickbooks',
                // Rapyd Payment
                'payment-methods/payment_rapyd',
                // Redde Payment
                'payment-methods/payment_redde',
                // Safepay Payment
                'payment-methods/payment_safepay',
                // Simplify Payments (Mastercard Simplify Commerce)
                'payment-methods/simplifypayment',
                // Skrill
                'payment-methods/skrill',
                // Square Payment
                'payment-methods/payment_square',
                // Stripe Payment
                'payment-methods/payment_stripe',
                // SumUp Payment
                'payment-methods/payment_sumup',
                // Tranzila
                'payment-methods/tranzila',
                // USAePay
                'payment-methods/payment_usaepay',
                // Viva.com Payment
                'payment-methods/payment_viva',
                // Voguepay
                'payment-methods/voguepay',
                // Worldline Payment
                'payment-methods/payment_worldline',
                // Worldpay Payment
                'payment-methods/payment_worldpay',
                // ZarinPal Payment
                'payment-methods/zarinpal',
            ],
        },
        {
            type: 'category',
            label: 'Shipping Methods',
            link: {
                type: 'generated-index',
                slug: '/shipping-methods',
            },
            items: [
                // AtoShip Multi-Carrier Shipping
                'shipping-methods/shipping_atoship',
                // Category Based Shipping
                'shipping-methods/categories',
                // Doordash
                'shipping-methods/shipping_doordash',
                // EasyShip Multi-Carrier Shipping
                'shipping-methods/shipping_easyship',
                // FedEx Shipping
                'shipping-methods/shipping-fedex',
                // Free Shipping
                'shipping-methods/shipping_free',
                // Pickup Options
                'shipping-methods/shipping-pickup',
                // Purolator Shipping
                'shipping-methods/purolator',
                // Shippo
                'shipping-methods/shipping_shippo',
                // Standard Shipping
                'shipping-methods/shipping-standard',
                // Unishippers LTL Freight
                'shipping-methods/shipping_unishippers',
                // UPS Global Checkout
                'shipping-methods/shipping_ups_global_checkout',
                // UPS Shipping
                'shipping-methods/ups-shipping',
                // USPS Advanced Shipping
                'shipping-methods/uspsadvanced',
            ],
        },
        {
            type: 'category',
            label: 'Reports',
            link: {
                type: 'doc',
                id: 'reports/index',
            },
            items: [
                // Itemized Report
                'reports/report-itemised',
                // Products Report
                'reports/report-products',
            ],
        },
        {
            type: 'category',
            label: 'J2Commerce Chat',
            link: {
                type: 'generated-index',
                slug: '/j2commerce-chat',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'j2commerce-chat',
                },
            ],
        },
        'plg_system_j2commercemcp',
        'rest-api',
    ],
};

export default sidebars;
