// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docSidebarV6: [
        'README',
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
                slug: '/getting-started',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'getting-started',
                },
            ],
        },
        {
            type: 'category',
            label: 'Configuration',
            link: {
                type: 'generated-index',
                slug: '/configuration',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'configuration',
                },
            ],
        },
        {
            type: 'category',
            label: 'Catalog',
            link: {
                type: 'generated-index',
                slug: '/catalog',
            },
            items: [
                {
                    type: 'category',
                    label: 'Product Types',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'catalog/product-types',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Design',
            link: {
                type: 'generated-index',
                slug: '/design',
            },
            items: [
                {
                    type: 'category',
                    label: 'Layout Overrides',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        'design/layout-overrides/app-overrides',
                        'design/layout-overrides/shipping-payment-overrides',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Layout',
            link: {
                type: 'generated-index',
                slug: '/layout',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'layout',
                },
            ],
        },
        {
            type: 'category',
            label: 'Apps and Extensions',
            link: {
                type: 'doc',
                id: 'apps-and-extensions/index',
            },
            items: [
                {
                    type: 'category',
                    label: 'Apps',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/apps',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Modules',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/modules',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Plugins',
                    link: {
                        type: 'generated-index',
                    },
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'apps-and-extensions/plugins',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Payment Methods',
            link: {
                type: 'generated-index',
                slug: '/payment-methods', // Custom slug removes /category prefix
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'payment-methods',
                },
            ],
        },
        {
            type: 'category',
            label: 'Shipping Methods',
            link: {
                type: 'generated-index',
                slug: '/shipping-methods',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'shipping-methods',
                },
            ],
        },
    ],
};

export default sidebars;
